version: '3.7'
services:
  db:
    image: mysql
    container_name: wx-db
    environment:
      - MYSQL_DATABASE=springboot-wx
      - MYSQL_ROOT_PASSWORD=test-wx
      - MYSQL_USER=test-wx
      - MYSQL_PASSWORD=test-wx
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=123456
    ports:
      - "16380:6379"