spring:
  application:
    name: web
# database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3309/springboot-test?useUnicode=true&characterEncoding=utf-8
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: pool-web
      maximum-pool-size: 50
      minimum-idle: 10
# email
  mail:
    host: smtp.126.com
    username: ${mail.username}
    password: ${mail.password}
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
# swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html

server:
  contextPath: /web
  port: 8082
  connection-timeout: 30000
  tomcat:
    max-connections: 200
    max-threads: 200
    min-spare-threads: 100
    uri-encoding: UTF-8

retry:
  maxAttempts: 2
  maxDelay: 600000