spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/springboot-test?useUnicode=true&characterEncoding=utf-8
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-on-migrate: true