spring:
  application:
    name: jpa
# database
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/springboot-jpa?useUnicode=true&characterEncoding=utf-8
    username: test-jpa
    password: test-jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: pool-jpa
      maximum-pool-size: 50
      minimum-idle: 10
  # https://springdoc.cn/spring-boot-and-spring-data-jpa/
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
      enabled: true
      location: ${java.io.tmpdir}
  security:
    user:
      name: test
      password: test1234

  data:
    redis:
      host: localhost     # Redis服务器地址
      port: 6379          # Redis服务器连接端口
      password: 123456    # Redis服务器连接密码（默认为空）
      database: 0         # Redis数据库索引（默认为0）
      timeout: 60s        # 连接空闲超过N(s秒、ms毫秒，不加单位时使用毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
      # Lettuce连接池配置
      lettuce:
        pool:
          max-active: 10  # 允许最大连接数，默认8（负值表示没有限制），推荐值：大于cpu * 2，通常为(cpu * 2) + 2
          max-idle: 8     # 最大空闲连接数，默认8，推荐值：cpu * 2
          min-idle: 0     # 最小空闲连接数，默认0
          max-wait: 5s    # 连接用完时，新的请求等待时间(s秒、ms毫秒)，超过该时间抛出异常，默认-1（负值表示没有限制）


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html

server:
  contextPath: /jpa
  port: 8083
  connection-timeout: 30000
  tomcat:
    max-connections: 200
    max-threads: 200
    min-spare-threads: 100
    uri-encoding: UTF-8

# print SQL parameters
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
      zalando:
        logbook:
          Logbook: TRACE # enable logbook log

# logbook日志配置
logbook:
  predicate:
    exclude:
      - path: /api-docs/**
      - path: /swagger-ui/**
      - path: /swagger-ui.html
      - path: /actuator/health
  format:
    style: splunk
  obfuscate:
    headers:
#      - Authorization
      - Cookie
    parameters:
      - password
    json-body-fields:
        - password
  write:
    level: TRACE
    max-body-size: 1000

wx:
  appId: ${appId}
  secret: ${secret}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full