spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-wx?useUnicode=true&characterEncoding=utf-8
    username: test-wx
    password: test-wx
    driver-class-name: com.mysql.cj.jdbc.Driver