spring:
  application:
    name: gradle
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/postgres?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: pool-gradle
      maximum-pool-size: 50
      minimum-idle: 10
  liquibase:
    enabled: false
  # https://springdoc.cn/spring-boot-and-spring-data-jpa/
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  security:
    user:
      name: test
      password: test1234

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html

server:
  contextPath: /gradle
  port: 8088
  connection-timeout: 30000
  tomcat:
    max-connections: 200
    max-threads: 200
    min-spare-threads: 100
    uri-encoding: UTF-8

# print SQL parameters
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
      zalando:
        logbook:
          Logbook: TRACE # enable logbook log

# logbook日志配置
logbook:
  predicate:
    exclude:
      - path: /api-docs/**
      - path: /swagger-ui/**
      - path: /swagger-ui.html
      - path: /actuator/health
  format:
    style: splunk
  obfuscate:
    headers:
      #      - Authorization
      - Cookie
    parameters:
      - password
    json-body-fields:
      - password
  write:
    level: TRACE
    max-body-size: 1000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full