version: '3.9'
services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 15432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres