spring:
  application:
    name: web
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/springboot-test?useUnicode=true&characterEncoding=utf-8
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: pool-web
      maximum-pool-size: 50
      minimum-idle: 10

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html

server:
  contextPath: /web
  port: 8082
  connection-timeout: 30000
  tomcat:
    max-connections: 200
    max-threads: 200
    min-spare-threads: 100
    uri-encoding: UTF-8

retry:
  maxAttempts: 2
  maxDelay: 1