spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/gradle-demo?useUnicode=true&characterEncoding=utf-8
    username: test-gradle
    password: test-gradle
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml