spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/postgres?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml