spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/springboot-jpa?useUnicode=true&characterEncoding=utf-8
    username: test-jpa
    password: test-jpa
    driver-class-name: com.mysql.cj.jdbc.Driver